version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      # target: development
    command: npm run start:dev auth
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    command: npm run start:dev user
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./.env
    ports:
      - '3001:3001'
      - '5001:5001'
    volumes:
      - .:/usr/src/app

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    command: npm run start:dev event
    environment:
      - NODE_ENV=production
      - PORT=3002
    env_file:
      - .env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app

  notification:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app

  check-in-out:
    build:
      context: .
      dockerfile: apps/check-in-out/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app

  participants:
    build:
      context: .
      dockerfile: apps/participants/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3005:3005'
    volumes:
      - .:/usr/src/app

  registration:
    build:
      context: .
      dockerfile: apps/registration/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3006:3006'
    volumes:
      - .:/usr/src/app

  email:
    build:
      context: .
      dockerfile: apps/email/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3007:3007'
    volumes:
      - .:/usr/src/app

  feedback-and-rating:
    build:
      context: .
      dockerfile: apps/feedback-and-rating/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3008:3008'
    volumes:
      - .:/usr/src/app

  schedule:
    build:
      context: .
      dockerfile: apps/schedule:/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3009:3009'
    volumes:
      - .:/usr/src/app

  document:
    build:
      context: .
      dockerfile: apps/document:/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3010:3010'
    volumes:
      - .:/usr/src/app

  forum:
    build:
      context: .
      dockerfile: apps/forum:/Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - '3011:3011'
    volumes:
      - .:/usr/src/app

networks:
  backend:
    driver: bridge
