version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - .env
    ports:
      - '3001:3001'
      - '5001:5001'
    volumes:
      - .:/usr/src/app

  
